---
variables:
  PROMETHEUS_VERSION: v2.14.0

stages:
  - lint

lint_yaml:
  stage: lint
  image: registry.getnoc.com/infrastructure/ansible_linter:master
  script:
    - yamllint docker-*.yml
  tags:
    - docker

lint_prometheus:
  stage: lint
  image:
    name: prom/prometheus:$PROMETHEUS_VERSION
    entrypoint: [""]
  script:
    - promtool check config ./data/prometheus/etc/prometheus.yml
  tags:
    - docker

lint_grafana:
  stage: lint
  image:
    name: grafana/grafana:6.3.6
    entrypoint: [""]
  script:
    - grafana-cli --config /etc/grafana/grafana.ini admin reset-admin-password admin
  tags:
    - docker

