---
variables:
  PROMETHEUS_VERSION: v2.14.0
  GET_SOURCES_ATTEMPTS: 3
#  GIT_CLEAN_FLAGS: none
#  GIT_STRATEGY: clone
  
stages:
  - .pre
  - test
  - lint


clear_stage:
  stage: .pre
  script:
    - chmod 777 -R ./
    - rm -rf ./*
  allow_failure: true
  tags:
    - shell

lint_bash:
  stage: lint
  before_script:
    - apk update && apk add bash shellcheck
  script:
    - shellcheck pre.sh
  tags:
    - docker
    
lint_yaml:
  stage: lint
  image: registry.getnoc.com/infrastructure/ansible_linter:master
  script:
    - yamllint docker-*.yml
  tags:
    - docker

lint_prometheus:
  stage: lint
  image:
    name: prom/prometheus:$PROMETHEUS_VERSION
    entrypoint: [""]
  script:
    - promtool check config ./data/prometheus/etc/prometheus.yml
  tags:
    - docker

lint_grafana:
  stage: lint
  image:
    name: grafana/grafana:6.3.6
    entrypoint: [""]
  script:
    - grafana-cli --homepath=/usr/share/grafana 
      --config ./data/grafana/etc/grafana.ini admin reset-admin-password admin
  tags:
    - docker

docker.compose:
  stage: test
  before_script:
    # TODO
    # need auth in registry
    # docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY or use
    - rm /home/gitlab-runner/.docker/config.json || true
 #   - rm -rf ./*
  script:
    - ./pre.sh all $PWD
    - docker --version
    - docker-compose --version
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up migrate
    - COMPOSE_HTTP_TIMEOUT=300 docker-compose up -d
    - COMPOSE_HTTP_TIMEOUT=300 docker-compose -f docker-compose-infra.yml up -d
  after_script:
    - docker-compose down -v
    - docker-compose -f docker-compose-infra.yml down -v
  tags:
    - shell
