---
variables:
  PROMETHEUS_VERSION: v2.14.0

stages:
  - lint
  - test
  
lint_yaml:
  stage: lint
  image: registry.getnoc.com/infrastructure/ansible_linter:master
  script:
    - yamllint docker-*.yml
  tags:
    - docker

lint_prometheus:
  stage: lint
  image:
    name: prom/prometheus:$PROMETHEUS_VERSION
    entrypoint: [""]
  script:
    - promtool check config ./data/prometheus/etc/prometheus.yml
  tags:
    - docker

lint_grafana:
  stage: lint
  image:
    name: grafana/grafana:6.3.6
    entrypoint: [""]
  script:
    - grafana-cli --homepath=/usr/share/grafana 
      --config ./data/grafana/etc/grafana.ini admin reset-admin-password admin
  tags:
    - docker

docker.compose:
  stage: test
  scripts:
    - ./pre.sh all
    - docker-compose migrate
    - docker-compose up -d