---
variables:
  PROMETHEUS_VERSION: v2.14.0

stages:
  - test
  - lint


lint_bash:
  stage: lint
  before_script:
    - apk update && apk add bash shellcheck
  script:
    - shellcheck pre.sh
  tags:
    - docker
    
lint_yaml:
  stage: lint
  image: registry.getnoc.com/infrastructure/ansible_linter:master
  script:
    - yamllint docker-*.yml
  tags:
    - docker

lint_prometheus:
  stage: lint
  image:
    name: prom/prometheus:$PROMETHEUS_VERSION
    entrypoint: [""]
  script:
    - promtool check config ./data/prometheus/etc/prometheus.yml
  tags:
    - docker

lint_grafana:
  stage: lint
  image:
    name: grafana/grafana:6.3.6
    entrypoint: [""]
  script:
    - grafana-cli --homepath=/usr/share/grafana 
      --config ./data/grafana/etc/grafana.ini admin reset-admin-password admin
  tags:
    - docker

docker.compose:
  stage: test
  image: centos:8
  before_script:
    - yum clean all && yum -y install epel-release
    - yum -y install docker curl
    - systemctl enable docker
    - systemctl start docker
    - curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /builds/noc/noc-dc/docker-compose
    - chmod +x /builds/noc/noc-dc/docker-compose
  script:
    - pwd && ls -la
    - env
    - find / -name docker-compose
#    - ldd docker-compose
    - ./pre.sh all /builds/noc/noc-dc
    #- pip install docker-compose==1.25.0
    - docker-compose up migrate
    - docker-compose up -d
  after_script:
    - docker system prune -a -f
  tags:
   - docker
