---
version: "2.4"

volumes:
  mongo_data_restore:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/mongorestore
      o: bind
      type: bind
  postgres_data_restore:
    driver: local
    driver_opts:
      device: $COMPOSEPATH/data/postgresrestore
      o: bind
      type: bind

services:
  mongorestore:
    image: mongo:4.0
    hostname: mongorestore
    command: >
      sh -c "
      mongorestore /home --host=mongo --drop --port=27017 -u noc -p noc -d noc
      "
    restart: "no"
    volumes:
      - mongo_data_restore:/home
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      traefik.enable: false

  postgresrestore:
    image: postgres:9.6
    hostname: postgresrestore
    command: >
      sh -c "set -xe
      && env
      && echo "-----------------------"
      && cat /home/developer_postgres_dump_2020_03_20.dump | psql -h postgres -U noc
      "
    restart: "no"
    volumes:
      - postgres_data_restore:/home
    environment:
      POSTGRES_USER: noc
      POSTGRES_DB: noc
      POSTGRES_PASSWORD: $NOC_PG_PASSWORD
      PGPASSWORD: $NOC_PG_PASSWORD
    logging:
      driver: $COMPOSE_LOG_DRIVER
      options:
        max-size: $COMPOSE_LOG_MAX_SIZE
        max-file: $COMPOSE_LOG_MAX_FILE
    labels:
      traefik.enable: false
